ci: print out tag env variable

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -108,58 +108,64 @@ jobs:
         id: get-tag
         run: |
           [[ ${{ contains(fromJSON('["prerelease", "premajor", "preminor", "prepatch"]'), inputs.release_type) }} ]] && echo "release-tag=canary" >> $GITHUB_OUTPUT || echo "release-tag=latest" >> $GITHUB_OUTPUT
+
+      - name: Print release tag
+        run: echo ${{env.release-tag}}
         env:
           release-tag: ${{steps.get-tag.outputs.release-tag}}
 
-      - name: Create npm token file
-        run: echo //registry.npmjs.org/:_authToken=${{secrets.NPMJS_PUBLISH_TOKEN}} > .npmrc
-
-      - name: Publish to NPM
-        uses: JS-DevTools/npm-publish@v1
-        id: npm-publish
-        with:
-          token: ${{ secrets.NPMJS_PUBLISH_TOKEN }}
-          tag: ${{ env.release-tag }}
-          registry: https://registry.npmjs.org/
-          access: public
-          package: ./${{matrix.package-folder}}/package.json
-        env:
-          release-tag: ${{steps.get-tag.outputs.release-tag}}
-
-      - name: Fail the workflow when unsuccessful publish
-        if: steps.npm-publish.outputs.type == 'none'
+      - name: Fail
         run: exit 1
 
-      - name: Show the result
-        run: echo "Version changed ${{ steps.npm-publish.outputs.old-version }} => ${{ steps.npm-publish.outputs.version }}"
+  #     - name: Create npm token file
+  #       run: echo //registry.npmjs.org/:_authToken=${{secrets.NPMJS_PUBLISH_TOKEN}} > .npmrc
 
-  cleanup-github:
-    name: Clean up git tags and PRs
-    runs-on: ubuntu-latest
-    needs: [bump-and-build, publish-npm-packages]
-    if: failure() && (needs.publish-npm-packages.result == 'failure')
-    env:
-      new_release_version: ${{ needs.bump-and-build.outputs.new_release_version }}
-      new_release_number: ${{ needs.bump-and-build.outputs.new_release_number}}
+  #     - name: Publish to NPM
+  #       uses: JS-DevTools/npm-publish@v1
+  #       id: npm-publish
+  #       with:
+  #         token: ${{ secrets.NPMJS_PUBLISH_TOKEN }}
+  #         tag: ${{ env.release-tag }}
+  #         registry: https://registry.npmjs.org/
+  #         access: public
+  #         package: ./${{matrix.package-folder}}/package.json
+  #       env:
+  #         release-tag: ${{steps.get-tag.outputs.release-tag}}
 
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-        with:
-          ref: 'release/${{env.new_release_version}}'
-          fetch-depth: 0
-          token: ${{ secrets.GITHUB_TOKEN }}
+  #     - name: Fail the workflow when unsuccessful publish
+  #       if: steps.npm-publish.outputs.type == 'none'
+  #       run: exit 1
 
-      - name: Cleanup GitHub releases
-        run: |
-          for crt_tag in $(git tag -l '*-${{env.new_release_number}}')
-          do
-            gh release delete $crt_tag -y --cleanup-tag
-          done
-        env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #     - name: Show the result
+  #       run: echo "Version changed ${{ steps.npm-publish.outputs.old-version }} => ${{ steps.npm-publish.outputs.version }}"
 
-      - name: Close PR
-        run: gh pr close release/${{env.new_release_version}} -d
-        env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  # cleanup-github:
+  #   name: Clean up git tags and PRs
+  #   runs-on: ubuntu-latest
+  #   needs: [bump-and-build, publish-npm-packages]
+  #   if: failure() && (needs.publish-npm-packages.result == 'failure')
+  #   env:
+  #     new_release_version: ${{ needs.bump-and-build.outputs.new_release_version }}
+  #     new_release_number: ${{ needs.bump-and-build.outputs.new_release_number}}
+
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v3
+  #       with:
+  #         ref: 'release/${{env.new_release_version}}'
+  #         fetch-depth: 0
+  #         token: ${{ secrets.GITHUB_TOKEN }}
+
+  #     - name: Cleanup GitHub releases
+  #       run: |
+  #         for crt_tag in $(git tag -l '*-${{env.new_release_number}}')
+  #         do
+  #           gh release delete $crt_tag -y --cleanup-tag
+  #         done
+  #       env:
+  #         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+  #     - name: Close PR
+  #       run: gh pr close release/${{env.new_release_version}} -d
+  #       env:
+  #         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
